/*** Menu texts ***************************************************/

char szMainMenuNew[] = "New card...";
char szMainMenuDisk[] = "Loading and Saving";
char szMainMenuOpen[] = "Open...";
char szMainMenuRecent[] = "Open again...";
char szMainMenuSave[] = "Save";
char szMainMenuSaveAs[] = "Save as...";
char szMainMenuCompilation[] = "Compilation";
char szMainMenuCompile[] = "Compile";
char szMainMenuTest[] = "Test";
char szMainMenuExecute[] = "Execute";
char szMainMenuQuit[] = "Quit";
char szMainMenuUndo[] = "Cancel";
char szMainMenuUndoLast[] = "Undo the last operation";
char szMainMenuUndoMnu[] = "Handle undo...";
char szMainMenuUndoHistory[] = "Display operation history";
char szMainMenuUndoFree[] = "Free the memory used by the undo";
char szMainMenuUndoCount[] = "Change the number of operations stored";
char szMainMenuSelRect[] = "Selection rectangle";
char szMainMenuCopy[] = "Copy";
char szMainMenuCut[] = "Cut";
char szMainMenuPaste[] = "Paste";
char szMainMenuLoadBrush[] = "Load...";
char szMainMenuLoadBrushInSel[] = "A saved area and paste it into the selection";
char szMainMenuLoadBrushInCopy[] = "A saved zone and store it in the copy memory";
char szMainMenuSaveBrush[] = "Save...";
char szMainMenuSelection[] = "The selection";
char szMainMenuCopyZone[] = "The copied zone";
char szMainMenuTransform[] = "Transformation...";
char szMainMenuRotateP90[] = "Rotation of 90° hours";
char szMainMenuRotateM90[] = "Rotate 90° counterclockwise";
char szMainMenuSymHorz[] = "Symmetry horizontal axis";
char szMainMenuSymVert[] = "Symmetry vertical axis";
char szMainMenuSelectChange[] = "Change selection";
char szMainMenuSelectAll[] = "Select all";
char szMainMenuSelectNone[] = "Deselect";
char szMainMenuSearch[] = "Search";
char szMainMenuFind[] = "Search...";
char szMainMenuPaintBrush[] = "Design pattern";
char szMainMenuWorldElem[] = "World elements";
char szMainMenuRooms[] = "Rooms";
char szMainMenuPaintMode[] = "Drawing mode";
char szMainMenuRect[] = "Rectangle";
char szMainMenuRectRnd[] = "Random Rectangle";
char szMainMenuRectFill[] = "Rectangle with fill";
char szMainMenuRectFillRnd[] = "Rectangle with random fill";
char szMainMenuCircle[] = "Ellipse";
char szMainMenuCircleRnd[] = "Random ellipse";
char szMainMenuCircleFill[] = "Ellipse with fill";
char szMainMenuCircleFillRnd[] = "Ellipse with random fill";
char szMainMenuLine[] = "Line";
char szMainMenuLineRnd[] = "Random line";
char szMainMenuPen[] = "Pencil";
char szMainMenuFill[] = "Fill";
char szMainMenuPutElem[] = "Place an element...";
char szMainMenuPutCreature[] = "Place a creature";
char szMainMenuPutDoor[] = "Place a door";
char szMainMenuPutTrap[] = "Place a trap";
char szMainMenuPutObject[] = "Place an object";
char szMainMenuPutMagicalObject[] = "Place a magic object";
char szMainMenuModifyCreature[] = "Modify the creature to place";
char szMainMenuModifyDoor[] = "Modify the door to place";
char szMainMenuModifyTrap[] = "Modify the trap to place";
char szMainMenuModifyObject[] = "Modify the object to place";
char szMainMenuModifyMagicalObject[] = "Modify the magic object to place";
char szMainMenuCreatures[] = "Manage creatures";
char szMainMenuDoorsTraps[] = "Manage doors and traps";
char szMainMenuObjects[] = "Objects management";
char szMainMenuOthers[] = "Others";
char szMainMenuHeros[] = "Heroes management";
char szMainMenuAreas[] = "Zone management";
char szMainMenuGates[] = "Gateways management";
char szMainMenuPaths[] = "Paths management";
char szMainMenuEffects[] = "Effects management";
char szMainMenuEvents[] = "Events management";
char szMainMenuCreaturesProperties[] = "Creature properties";
char szMainMenuGameProperties[] = "Item properties";
char szMainMenuMapProperties[] = "Map properties";
char szMainMenuThumbnail[] = "Reduction";
char szMainMenuFullScreen[] = "Full screen map";
char szMainMenuMapStats[] = "Map statistics";
char szMainMenuWindows[] = "Windows";
char szMainMenuToolbar[] = "Toolbar";
char szMainMenuMinimap[] = "Thumbnail map && Information";
char szMainMenuMinimapParams[] = "Miniature map parameters";
char szMainMenuKeepProps[] = "Keep proportions";
char szMainMenuDisplayCreatures[] = "Display creatures";
char szMainMenuDisplayDoors[] = "Display doors";
char szMainMenuDisplayTraps[] = "Display traps";
char szMainMenuDisplayMagics[] = "Display magic objects";
char szMainMenuMap[] = "Map";
char szMainMenuFlagTerrain[] = "Terrain";
char szMainMenuFlagCreatures[] = "Creatures";
char szMainMenuFlagDoors[] = "Doors";
char szMainMenuFlagTraps[] = "Traps";
char szMainMenuFlagMagicals[] = "Magical objects";
char szMainMenuFlagObjects[] = "Objects";
char szMainMenuFlagAreas[] = "Areas";
char szMainMenuFlagPaths[] = "Paths";
char szMainMenuFlagGates[] = "Passages";
char szMainMenuFlagEffects[] = "Effects";
char szMainMenuFlagCameras[] = "Cameras";
char szMainMenuOptions[] = "Options";
char szMainMenuMoreDetails[] = "Detail the number of creatures";
char szMainMenuExpandGates[] = "Expand gateways";
char szMainMenuObjectsColor[] = "Use player colors for objects";
char szMainMenuMagicsColor[] = "Use player colors for magic items";
char szMainMenuProperties[] = "Change program parameters";
char szMainMenuPropertiesSave[] = "Save parameters on exit";
char szMainMenuPropertiesSaveNow[] = "Save settings now";
char szMainMenuHelpContent[] = "Content";
char szMainMenuHelpFirstRun[] = "First steps";
char szMainMenuHelpVersions[] = "Map versions";
char szMainMenuAbout[] = "About...";
char szMainMenuHeroPortals[] = "Hero Portals";
char szMainMenuPlayers[] = "Players";

char szMainMenuKeyNew[] = "Shift + Ctrl + N";
char szMainMenuKeyOpen[] = "Ctrl + O";
char szMainMenuKeySave[] = "Ctrl + S";
char szMainMenuKeyCompile[] = "Shift + Ctrl + C";
char szMainMenuKeyTest[] = "Shift + Ctrl + T";
char szMainMenuKeyExecute[] = "Shift + Ctrl + E";
char szMainMenuKeyUndoLast[] = "Ctrl + Z";
char szMainMenuKeyCopy[] = "Ctrl + C";
char szMainMenuKeyCut[] = "Ctrl + X";
char szMainMenuKeyPaste[] = "Ctrl + V";
char szMainMenuKeyRotateP90[] = "Ctrl + R";
char szMainMenuKeyRotateM90[] = "Shift + Ctrl + R";
char szMainMenuKeySymHorz[] = "Ctrl + Y";
char szMainMenuKeySymVert[] = "Shift + Ctrl + Y";
char szMainMenuKeySelectAll[] = "Ctrl + A";
char szMainMenuKeySelectNone[] = "Ctrl + N";
char szMainMenuKeyFind[] = "Ctrl + F";
char szMainMenuKeyRect[] = "Ctrl + f1";
char szMainMenuKeyRectFill[] = "Ctrl + f2";
char szMainMenuKeyCircle[] = "Ctrl + f3";
char szMainMenuKeyCircleFill[] = "Ctrl + f4";
char szMainMenuKeyLine[] = "Ctrl + f5";
char szMainMenuKeyPen[] = "Ctrl + f6";
char szMainMenuKeyFill[] = "Ctrl + f7";
char szMainMenuKeyPutCreature[] = "Shift + Ctrl + f1";
char szMainMenuKeyPutDoor[] = "Shift + Ctrl + f2";
char szMainMenuKeyPutTrap[] = "Shift + Ctrl + f3";
char szMainMenuKeyPutObject[] = "Shift + Ctrl + f4";
char szMainMenuKeyPutMagicalObject[] = "Shift + Ctrl + f5";
char szMainMenuKeyHelp[] = "f1";

char szMenuPlayers00[] = "Player selection";
char szMenuPlayers01[] = "Hero";
char szMenuPlayers02[] = "Neutral";
char szMenuPlayers03[] = "Keeper 1";
char szMenuPlayers04[] = "Keeper 2";
char szMenuPlayers05[] = "Keeper 3";
char szMenuPlayers06[] = "Keeper 4";
char szMenuPlayers07[] = "Keeper 5";
char szMenuCancel[] = "Abort";

char szMenuGate00[] = "Hero Portal Selection";
char szMenuGate01[] = "1 -- Portal in large vaulted room -- Southbound";
char szMenuGate02[] = " 2 -- Portal inlaid in hard rock";
char szMenuGate03[] = " 3 -- Vaulted portal";
char szMenuGate04[] = " 4 -- Portal in large presentation room -- Southward";
char szMenuGate06[] = " 6 -- Horizontal portal";
char szMenuGate07[] = " 7 -- Vertical portal";

char szMenuGateDM1[] = "(L 3 x Hmin 1)";
char szMenuGateDM2[] = "(Lmin 1 x Hmin 1)";
char szMenuGateDM3[] = "(L 2 x H 2)";
char szMenuGateDM4[] = "(L 3 x Hmin 2)";
char szMenuGateDM5[] = "(Lmin 1 x Hmin 1)";
char szMenuGateDM6[] = "(L 3 x H 1)";
char szMenuGateDM7[] = "(L 1 x H 3)";

char szMenuZoom[] = "Zoom selection";
char szMenuZoomM5[] = "10x10 pixels"; // 00
char szMenuZoomM4[] = "16x16 pixels"; // 01
char szMenuZoomM3[] = "20x20 pixels"; // 02
char szMenuZoomM2[] = "32x32 pixels"; // 03
char szMenuZoomM1[] = "40x40 pixels"; // 04
char szMenuZoomM0[] = "48x48 pixels (default)"; // 05
char szMenuZoomP1[] = "60x60 pixels"; // 06
char szMenuZoomP2[] = "80x80 pixels"; // 07
char szMenuZoomP3[] = "96x96 pixels"; // 08
char szMenuZoomP4[] = "100x100 pixels"; // 09
char szMenuZoomP5[] = "128x128 pixels"; // 10
char szMenuZoomU0[] = "%ldx%ld pixels (custom)";// 11
char szMenuZoomU1[] = "Change custom zoom";
char szMenuZoomUT[] = "000x000 pixels (custom)";