
#define DIALOG_CLASS "MapEditorDialog32"
#define DIALOG_PATHSCLASS "MapEditorPathsDialog32"

#define MENU_SAFEFILE "Load automatic backup"
#define MENU_REMOVEOBSOLETE "Remove from the list maps that no longer exist"
#define MENU_REMOVEALL "Reset the list"

/*** Dialog texts **********************************************/

#define DIALOG_VARIABLE "Variable"
#define DIALOG_TIMER "Counter"
#define DIALOG_DOORTITLE "Door selection..."
#define DIALOG_TRAPTITLE "Selection of a trap..."
#define DIALOG_CREATURETITLE "Selection of a creature..."
#define DIALOG_MAGICTITLE "Selection of a magic object..."
#define DIALOG_THINGTITLE "Selection of an object..."
#define DIALOG_NULL ""
#define DIALOG_PLAYER "Player"
#define DIALOG_CREATUREOPTIONS "Creature options"
#define DIALOG_HEROSPARAMS "Hero settings"
#define DIALOG_HEROSOPTIONS "Hero options"
#define DIALOG_HEROSOBJECTIVES "Objective"
#define DIALOG_ALLOPTIONS "Options"
#define DIALOG_FILEWIDTH "Width:"
#define DIALOG_FILEHEIGHT "Height:"
#define DIALOG_FILECREATURES "Creatures:"
#define DIALOG_FILEDOORS "Doors:"
#define DIALOG_FILETRAPS "Traps:"
#define DIALOG_FILEOBJECTS "Objects:"
#define DIALOG_FILEMAGICS "Mag. objects:"
#define DIALOG_DOORTYPE "Door type"
#define DIALOG_DOORCLOSED "Door closed"
#define DIALOG_DOORBLUEPRINT "Sketch"
#define DIALOG_OK "Ok"
#define DIALOG_ABORT "Abort"
#define DIALOG_TRAPTYPE "Type of trap"
#define DIALOG_CREATURETYPE "Creature type"
#define DIALOG_VITALITY "Health"
#define DIALOG_MAGICTYPE "Type of magic object"
#define DIALOG_THINGTYPE "Type of object"

#define DIALOG_EXITERR "Card creator for Dungeon Keeper II®"
#define DIALOG_EXIT "The program did not finish normally!"
#define DIALOG_EXITLOADSAFE "Load automatic backup"
#define DIALOG_EXITCONTINUE "Continue without loading the autobackup"

#define DIALOG_OPTIONSCREATURE04    "The creature leads the group"
#define DIALOG_OPTIONSCREATURE02    "Creature assists the leader"
#define DIALOG_OPTIONSCREATURE04B   "The creature dies instantly"
#define DIALOG_OPTIONSCREATURE00    "The creature is independent"
#define DIALOG_OPTIONSCREATURE01    "Creature can attack"
#define DIALOG_OPTIONSCREATURE08    "The creature can be attacked"
#define DIALOG_OPTIONSCREATURE10    "The creature can join the heroes' lair"
#define DIALOG_OPTIONSCREATURE20    "The creature can free its allies in prison"
#define DIALOG_OPTIONSCREATURE40    "The creature is dropped at the indicated place"
#define DIALOG_OPTIONSCREATURE80    "The creature appears stunned"
#define DIALOG_OPTIONSHEROS01       "The creature destroys the enemy's rooms"
#define DIALOG_OPTIONSHEROS04       "The creature dies instantly"
#define DIALOG_OPTIONSHEROS02       "The creature is a toy"
#define DIALOG_OPTIONSHEROS08       "Creature is a mercenary"
#define DIALOG_OPTIONSOBJECTIVE0B   "Destroy enemy rooms"
#define DIALOG_OPTIONSOBJECTIVE0C   "Destroy the enemy walls"
#define DIALOG_OPTIONSOBJECTIVE0D   "Steal the enemy's gold"
#define DIALOG_OPTIONSOBJECTIVE0E   "Steal enemy's spells"
#define DIALOG_OPTIONSOBJECTIVE11   "Steal the enemy's crates"
#define DIALOG_OPTIONSOBJECTIVE12   "Kill enemy's creatures"
#define DIALOG_OPTIONSOBJECTIVE13   "Attack the enemy"
#define DIALOG_OPTIONSOBJECTIVE16   "Wait"
#define DIALOG_OPTIONSOBJECTIVE17   "Join an area"
#define DIALOG_OPTIONSOBJECTIVE1B   "Escape"

#define DIALOG_UNDOTITLE "History of the cancellation"
#define DIALOG_UNDOLIST "Memorized operations"
#define DIALOG_UNDOTOTAL "Total operations"
#define DIALOG_UNDOCHANGES "Changes made"
#define DIALOG_UNDOMEMORY "Memory used (in bytes)"

#define DIALOG_SELTITLE "Changes made to the selection rectangle"
#define DIALOG_SELX "X:"
#define DIALOG_SELY "Y:"
#define DIALOG_SELWIDTH "Width:"
#define DIALOG_SELHEIGHT "Height:"

#define DIALOG_THUMBTITLE "Discount display options"
#define DIALOG_THUMBWORLD "World"
#define DIALOG_THUMBWORLD1 "Limits"
#define DIALOG_THUMBWORLD2 "Water"
#define DIALOG_THUMBWORLD3 "Wash"
#define DIALOG_THUMBWORLD4 "Gold"
#define DIALOG_THUMBWORLD5 "Gems"
#define DIALOG_THUMBWORLD6 "Impenetrable rock"
#define DIALOG_THUMBWORLD7 "Rock"
#define DIALOG_THUMBWORLD8 "Unclaimed land"
#define DIALOG_THUMBWORLD9 "Heroes' resting rooms"
#define DIALOG_THUMBPLAYERS "Players"
#define DIALOG_THUMBPLAYERS1 "Walls and fields claimed"
#define DIALOG_THUMBPLAYERS2 "Rooms"
#define DIALOG_THUMBPLAYERS3 "Portals"
#define DIALOG_THUMBPLAYERS4 "Dungeon Hearts"
#define DIALOG_THUMBCOLOR "Color of hidden areas"
#define DIALOG_THUMBCOLORKEY "This color must be transparent"

#define DIALOG_MNGRTITLE "Element manager"
#define DIALOG_MNGRPARAMS "New element parameters"
#define DIALOG_MNGRCREATUREOPT "Modify creature options"
#define DIALOG_MNGRHEROOPT "Change hero options"
#define DIALOG_MNGROBJECTIVEOPT		"Modifier l'objectif"
#define DIALOG_MNGRMODIFYPARAMS "Modify"
#define DIALOG_MNGRMODIFYASK "Request options before modifying"
#define DIALOG_MNGRMODIFYPREVIEW "Show preview before editing"
#define DIALOG_MNGRMODIFYSTART "<< Edit"
#define DIALOG_MNGRADDPARAMS "Add"
#define DIALOG_MNGRADDASK "Request parameters before adding"
#define DIALOG_MNGRADDPREVIEW "Show preview before adding"
#define DIALOG_MNGRADDSTART "<< Add"
#define DIALOG_MNGRPOS "Positions"
#define DIALOG_MNGRVIEW "View"
#define DIALOG_MNGRKILL "Delete"
#define DIALOG_MNGRSELECTALL "Select all"
#define DIALOG_MNGROPTIONS "Options"
#define DIALOG_MNGRMODIFY "Modify"
#define DIALOG_MNGRUNDO "Undo changes"
#define DIALOG_MNGRCLOSE "Close"
#define DIALOG_MNGRSHOW "Click here to continue"

#define DIALOG_MNGRMODOPTIONS		"Options de modification"
#define DIALOG_MNGRMODGENERAL "General options"
#define DIALOG_MNGRMODPOSITION "Modify position"
#define DIALOG_MNGRMODSAMEPOS "Use same position for all"
#define DIALOG_MNGRMODRELATIVEPOS "Use relative position"
#define DIALOG_MNGRMODTYPE		"Modifier le type"
#define DIALOG_MNGRMODOWNER		"Modifier le d�tenteur"
#define DIALOG_MNGRMODREMPLACE "Replacement"
#define DIALOG_MNGRMODREMPALL "Replace all"
#define DIALOG_MNGRMODREMSAME		"Ne remplacer que les �l�ments identiques"
#define DIALOG_MNGRMODREMSAMEFAMILY "Replace only elements of the same family"
#define DIALOG_MNGRMODREMNONE "Don't replace anything"
#define DIALOG_MNGRMODREMASK "Show preview"
#define DIALOG_MNGRMODPROBLEMS		"En cas de probl�me"
#define DIALOG_MNGRMODIGNORETERRAIN "Ignore incompatible terrains"
#define DIALOG_MNGRMODIGNOREFATALS "Ignore fatal terrain"
#define DIALOG_MNGRMODIGNOREENEMIES "Ignore enemy terrain"
#define DIALOG_MNGRMODIGNOREINCOMP "Ignore incompatibilities"
#define DIALOG_MNGRMODIGNOREASK "Show preview"
#define DIALOG_MNGRMODSPECIALS "Special parameters"
#define DIALOG_MNGRMODLEVEL "Change level"
#define DIALOG_MNGRMODGOLD "Change gold"
#define DIALOG_MNGRMODHEALTH "Change health"
#define DIALOG_MNGRMODCROPTIONS "Modify creature options"
#define DIALOG_MNGRMODCROPTALL "Select all
#define DIALOG_MNGRMODCROPTSELECT "Select separately
#define DIALOG_MNGRMODHROPTIONS "Change hero options"
#define DIALOG_MNGRMODOBJECTIVE		"Change Objective"
#define DIALOG_MNGRMODSTATUS "Change status"
#define DIALOG_MNGRMODDATA		"Modifier la donn�e"

#define DIALOG_MNGRADDOPTIONS "Add options"
#define DIALOG_MNGRADDOPTPARAMS "Add parameters"
#define DIALOG_MNGRADDPOS		"Ajouter � la position sp�cifi�e"
#define DIALOG_MNGRADDRECT		"Ajouter dans tout le rectangle"
#define DIALOG_MNGRADDRECTRANDOM "Add randomly in the whole rectangle"
#define DIALOG_MNGRADDRANDOM "Chances (1/x)"
#define DIALOG_MNGRADDRANDOMOFTEN "Often"
#define DIALOG_MNGRADDRANDOMRARELY "Rarely"

#define DIALOG_MNGRPREVIEW		"Aper�u des changements"
#define DIALOG_MNGRPREVBEFORE "Before"
#define DIALOG_MNGRPREVAFTER "After"
#define DIALOG_MNGRPREVPROBLEMS "Problems"
#define DIALOG_MNGRPREVACTIONS "Actions"
#define DIALOG_MNGRPREVIGNORE "Do nothing"
#define DIALOG_MNGRPREVREMOVE "Delete"
#define DIALOG_MNGRPREVMODIFY "Modify"
#define DIALOG_MNGRPREVADD "Add"
#define DIALOG_MNGRPREVCONTINUE "Continue"

#define DIALOG_HEROSTITLE "Heroes..."
#define DIALOG_HEROSLIST		"Liste des bandes"
#define DIALOG_HEROSMODIFY "Modify"
#define DIALOG_HEROSKILL "Delete"
#define DIALOG_HEROSADD "Add"
#define DIALOG_HEROSCLOSE "Close"
#define DIALOG_HEROSEDITTITLE "Add and modify a hero band..."
#define DIALOG_HEROSEDITNAME "Name of the hero band"
#define DIALOG_HEROSEDITCREATURES "List of creatures
#define DIALOG_HEROSEDITPARAMS "Selected creature settings"
#define DIALOG_HEROSEDITLEVEL "Level"
#define DIALOG_HEROSEDITOPTIONS "Options"
#define DIALOG_HEROSEDITOBJECTIVE "Objective"
#define DIALOG_HEROSEDITADD "Add >>"
#define DIALOG_HEROSEDITREMPLACE "Replace >>"
#define DIALOG_HEROSEDITBAND "Band of heroes"
#define DIALOG_HEROSEDITKILL "Delete the selected hero(s)"
#define DIALOG_HEROSEDITMODIFY		"Modifier le h�ro s�lectionn�"

#define DIALOG_AREARECT			"Selection rectangle"
#define DIALOG_AREASTART "Start positions"
#define DIALOG_AREAEND "End positions"
#define DIALOG_AREASEPARATOR "/"
#define DIALOG_AREARECTCOLOR "Color of the rectangle"
#define DIALOG_AREAMODIFY "Modify"
#define DIALOG_AREATEXTCOLOR "Text color"
#define DIALOG_AREANAME "Name"
#define DIALOG_AREAINFO "Description"
#define DIALOG_AREAOPTIONS "Options"
#define DIALOG_AREAADD "Add >>"
#define DIALOG_AREALIST "List
#define DIALOG_AREAKILL "Delete"
#define DIALOG_AREAMODIFY "Modify"
#define DIALOG_AREACLOSE "Close"
#define DIALOG_AREAMODIFYRECT "Rectangle to modify"
#define DIALOG_AREAGETRECT "<<"
#define DIALOG_AREAOPTTITLE "Area options"
#define DIALOG_AREAOPTHEROLAIR "Heroes Den"
#define DIALOG_AREAOPTIGNORESOLID "Ignore solid parts"
#define DIALOG_AREAOPTVISIBLE "Visible through the fog of war"
#define DIALOG_AREAOPTTOOLS "Hero box (small dungeon)"
#define DIALOG_EFFECTOPTTITLE "Effect settings"
#define DIALOG_EFFECTOPTFREQ "Effect frequency"
#define DIALOG_EFFECTOPTEFFECT1 "First effect"
#define DIALOG_EFFECTOPTEFFECT2 "Second effect"
#define DIALOG_EFFECTOPTEFFECT3 "Third effect"
#define DIALOG_EFFECTOPTEFFECT4 "Fourth effect"
#define DIALOG_EFFECTOPTOFTEN "Often"
#define DIALOG_EFFECTOPTRARELY "Very rarely"
#define DIALOG_GATEOPTTITLE "Automatically add passages"
#define DIALOG_GATEOPTADDPARAMS "Add parameters"
#define DIALOG_GATEOPTGATES "Add the necessary passages..."
#define DIALOG_GATEOPTGATES0 "...to display"
#define DIALOG_GATEOPTGATES1 "...to destruction"
#define DIALOG_GATEOPTGATES2 "...to hero release"
#define DIALOG_GATEOPTAREAS "Add necessary areas..."
#define DIALOG_GATEOPTTRIGGERS "Add the events"
#define DIALOG_GATEOPTDISPPARAMS "Display parameters"
#define DIALOG_GATEOPTDISPTYPE "Settings for..."
#define DIALOG_GATEOPTGENERATE	"Add"

#define DIALOG_AREAPATHTITLE		"Edition des chemins de ronde"
#define DIALOG_AREAPATHLIST "List of paths"
#define DIALOG_AREAPATHNEW "New"
#define DIALOG_AREAPATHADD "Add"
#define DIALOG_AREAPATHINS "Insert"
#define DIALOG_AREAPATHSUB "Delete"
#define DIALOG_AREAPATHMOD "Pause"
#define DIALOG_AREAPATHCLOSE "Close"
#define DIALOG_AREAPATHPTTITLE "Select a zone"
#define DIALOG_AREAPATHPTLIST "Zone list"
#define DIALOG_AREAPATHPTDELAY "Number of seconds to wait before reaching the next zone"

#define DIALOG_MAPPROPSTITLE "Map properties"
#define DIALOG_MAPPROPSINFO		"Informations de la carte"
#define DIALOG_MAPPROPSNAME "Card name"
#define DIALOG_MAPPROPSINFOTEXTS "Descriptions"
#define DIALOG_MAPPROPSDIM		"Map dimensions"
#define DIALOG_MAPPROPSWIDTH "Width:"
#define DIALOG_MAPPROPSHEIGHT "Height:"
#define DIALOG_MAPPROPSRESET "Reset"
#define DIALOG_MAPPROPSKEEPERS "Player properties"
#define DIALOG_MAPPROPSHEROS "Heroes"
#define DIALOG_MAPPROPSNEUTRAL "Neutral"
#define DIALOG_MAPPROPSKEEPER1 "Keeper 1"
#define DIALOG_MAPPROPSKEEPER2 "Keeper 2"
#define DIALOG_MAPPROPSKEEPER3 "Keeper 3"
#define DIALOG_MAPPROPSKEEPER4 "Keeper 4"
#define DIALOG_MAPPROPSKEEPER5 "Keeper 5"
#define DIALOG_MAPPROPSALLIES "Alliances"
#define DIALOG_MAPPROPSCREATURES "Creatures"
#define DIALOG_MAPPROPSVOICES "Voices"
#define DIALOG_MAPPROPSTEXTS "Texts"
#define DIALOG_MAPPROPSVARIABLES "Variables"
#define DIALOG_MAPPROPSOPTIONS "Options"

#define DIALOG_MAPPLAYERTITLE "Player properties"
#define DIALOG_MAPPLAYERINFO		"Informations sur le joueur"
#define DIALOG_MAPPLAYERNAME "Name"
#define DIALOG_MAPPLAYERCPU "Computer"
#define DIALOG_MAPPLAYERCPUOPTS "Settings"
#define DIALOG_MAPPLAYERTREASURY "Treasure room capacity"
#define DIALOG_MAPPLAYERCAMERA "Camera start position"
#define DIALOG_MAPPLAYERTREASURY "Treasure room capacity"
#define DIALOG_MAPPLAYERCAMERASELECT "Select position"
#define DIALOG_MAPPLAYERELEMENTS "List of elements"
#define DIALOG_MAPPLAYEROPTIONS "Options of the selected items" 
#define DIALOG_MAPPLAYERCAMERASELECT "Select position"
#define DIALOG_MAPPLAYERNONE "Do not specify anything" 
#define DIALOG_MAPPLAYERNA "Unavailable"
#define DIALOG_MAPPLAYERRESEARCH "To be searched"
#define DIALOG_MAPPLAYEROK "Acquired from the start"
#define DIALOG_MAPPLAYERLOCKED "Locked"
#define DIALOG_MAPPLAYERCRLIST "List of creatures"
#define DIALOG_MAPPLAYERCRSELECT "Selected creatures"
#define DIALOG_MAPPLAYERCRMAX "Maximum number"
#define DIALOG_MAPPLAYERERCRCANT "Do not specify"
#define DIALOG_MAPPLAYERDEFAULT "Default"

#define DIALOG_MAPCPUSECONDS "second(s)"
#define DIALOG_MAPCPUTILES "square(s)"
#define DIALOG_MAPCPUCREATURESAMOUNT "creature(s)"
#define DIALOG_MAPCPUPERCENT "%"
#define DIALOG_MAPCPU0 "0%"
#define DIALOG_MAPCPU100 "100"
#define DIALOG_MAPCPUPRESETS "Definitions"
#define DIALOG_MAPCPUPRESETSLIST "List of definitions"
#define DIALOG_MAPCPUPRESETSUSE "Use default values for this definition"
#define DIALOG_MAPCPUBUILDS "Constructions"
#define DIALOG_MAPCPUAREA "Expansion area"
#define DIALOG_MAPCPUX1 "X1"
#define DIALOG_MAPCPUY1 "Y1"
#define DIALOG_MAPCPUX2 "X2"
#define DIALOG_MAPCPUY2 "Y2"
#define DIALOG_MAPCPUUSEAREA "Use the coordinates of the area..."
#define DIALOG_MAPCPUORDER "Construction order"
#define DIALOG_MAPCPUROOMS "Rooms"
#define DIALOG_MAPCPUROOMSWAIT "Waiting time before building a discovered room:"
#define DIALOG_MAPCPUROOMSLOST "Build lost rooms after"
#define DIALOG_MAPCPUROOMSSIZE "Room size:"
#define DIALOG_MAPCPUROOMSSPACE "Number of squares between each room:"
#define DIALOG_MAPCPUROOMSNEAR "Distance between rooms that must be close:"
#define DIALOG_MAPCPUROOMSCORRIDOR "Corridor style:"
#define DIALOG_MAPCPUROOMSEXPAND "When the available space in a room becomes insufficient,"
#define DIALOG_MAPCPUROOMSNEUTRAL1 "Dig down to the neutral rooms located at"
#define DIALOG_MAPCPUROOMSNEUTRAL2 "square(s) in the heart of the dungeon"
#define DIALOG_MAPCPUROOMSNEUTRAL3 "square(s) of the claimed areas"
#define DIALOG_MAPCPUROOMSSELL "sell captured rooms when cash is needed"
#define DIALOG_MAPCPUROOMSFLEXIBILITY "Flexibility:"
#define DIALOG_MAPCPUROOMSIDLE "Create empty zones in case of inactivity"
#define DIALOG_MAPCPUROOMSEXPANDLAIR "Create a larger den after claiming a portal"
#define DIALOG_MAPCPUDOORSNTRAPS "Doors && traps"
#define DIALOG_MAPCPUDTTRAPS "The guard will use traps instead..."
#define DIALOG_MAPCPUDTAGGRESSIVE "Aggressive"
#define DIALOG_MAPCPUDTDEFENSIVE "Defensive
#define DIALOG_MAPCPUDTPREF "The goalie will more likely use..."
#define DIALOG_MAPCPUDTTRAP "Traps"
#define DIALOG_MAPCPUDTDOOR "Doors"
#define DIALOG_MAPCPUDTBESTDOOR "Build the best doors"
#define DIALOG_MAPCPUDTWORSTDOOR "Build the worst doors
#define DIALOG_MAPCPUDTRANDOMDOOR "Choose the doors randomly
#define DIALOG_MAPCPUDTCORRIDOR "Place rock traps in long corridors"
#define DIALOG_MAPCPUDTBREACH "Place rock traps in the corridors leading to the breaches"
#define DIALOG_MAPCPUDTCHANCE "Probability that the guard will build doors and traps..."
#define DIALOG_MAPCPUSPELLS "Spells"
#define DIALOG_MAPCPUBATTLESPELL "Frequency of use of spells in combat:"
#define DIALOG_MAPCPUOFTEN "Often"
#define DIALOG_MAPCPURARELY "Rarely"
#define DIALOG_MAPCPUSPELLPOWER "The guard uses spells instead..."
#define DIALOG_MAPCPUSPELLHIGHPOWER "Powerful"
#define DIALOG_MAPCPUSPELLLOPOWER "Not very powerful
#define DIALOG_MAPCPUSIGHTOFEVIL "Use the devil's eye spell..."
#define DIALOG_MAPCPUCALLTOARMS "Use the rallying spell..."
#define DIALOG_MAPCPULIGHTNING "Use the lightning spell if the enemy is on the water"
#define DIALOG_MAPCPUCREATURES "Creatures
#define DIALOG_MAPCPUSADTOHAPPY "The guardian tries to make the unhappy creatures happy"
#define DIALOG_MAPCPUUNGRYTOHAPPY "The guardian tries to make the angry creatures happy"
#define DIALOG_MAPCPUSACKUNGRY "The guardian fires the angry creatures"
#define DIALOG_MAPCPUSACKUNUSED "The guardian fires the useless creatures if better ones come along"
#define DIALOG_MAPCPUSACKMETHOD "The guardian kicks out his creatures by..."
#define DIALOG_MAPCPUIMPSMAX "Maximum number of goblins:"
#define DIALOG_MAPCPUDONTSLAP "The guardian does not hit his creatures"
#define DIALOG_MAPCPUFIRSTBATTLE "First attack
#define DIALOG_MAPCPUCONDITIONS "Attack conditions
#define DIALOG_MAPCPULEVEL "All creatures have reached level:"
#define DIALOG_MAPCPUOWN "Guardian has at least"
#define DIALOG_MAPCPUTHREAT "The threat represented by the creatures is"
#define DIALOG_MAPCPUTHREAT2 "% greater than that of the enemy".
#define DIALOG_MAPCPUALLROOMS "All the rooms have been built"
#define DIALOG_MAPCPUALLSPELLS "All spells have been found"
#define DIALOG_MAPCPUSTYLE "Type of attack
#define DIALOG_MAPCPUBREACHTO "The guard first tries to attack..."
#define DIALOG_MAPCPUDIGTO "The guard tries to create a breach..."
#define DIALOG_MAPCPUCOUNT "Attack by"
#define DIALOG_MAPCPUCOUNT2 "side(s)"
#define DIALOG_MAPCPUFORCES "Creatures to use in first attack:"
#define DIALOG_MAPCPUFORCES2 "% of total"
#define DIALOG_MAPCPUMAINCONDITION "General attack behavior"
#define DIALOG_MAPCPUCOUNTERATTACK "Counterattack in case of invasion of the dungeon by the enemy"
#define DIALOG_MAPCPUDONTATTACK "Never attack the enemy
#define DIALOG_MAPCPUBATTLES "Fights"
#define DIALOG_MAPCPUBTHREAT1 "The threat represented by the dropped creatures must match"
#define DIALOG_MAPCPUBTHREAT2 "% of the threat represented by the enemy"
#define DIALOG_MAPCPUBPELL "Use spells"
#define DIALOG_MAPCPUBJAIL1 "Attempt to imprison" 
#define DIALOG_MAPCPUBJAIL2 "% of enemy creatures
#define DIALOG_MAPCPUBPULLOUT "Remove creatures from the battle if the enemy is outnumbered and no reinforcements are available"
#define DIALOG_MAPCPUBHEALTH1 "If creature's vitality is equal to "
#define DIALOG_MAPCPUBHEALTH2 "% of its total and it is not on its field, move it to a den or temple"
#define DIALOG_MAPCPUBCALLTOARMS "Rallying flag"
#define DIALOG_MAPCPUBCALLTOARMS1 "Place it where the threat is greater than"
#define DIALOG_MAPCPUBCALLTOARMS2 "Remove it after"
#define DIALOG_MAPCPUBCALLTOARMS3 "Remove it if less than"
#define DIALOG_MAPCPUBCALLTOARMS4 "Enemy creatures are in the"
#define DIALOG_MAPCPUBCALLTOARMS5 "surrounding squares"
#define DIALOG_MAPCPUBCALLTOARMS6 "Remove it if there are less than"
#define DIALOG_MAPCPUBCALLTOARMS7 "creatures available"
#define DIALOG_MAPCPUBATTACKAGAIN "Wait between each attack:"
#define DIALOG_MAPCPUOTHER "Other"
#define DIALOG_MAPCPUOLIBRARY "Probability of using the hidden library:"
#define DIALOG_MAPCPUOJAILED "Fate of trapped creatures:"
#define DIALOG_MAPCPUOGOLDMINED "Collect gold until the amount is greater than:"
#define DIALOG_MAPCPUOSPECIALS1 "Number of squares to explore in order to search for secrets:"
#define DIALOG_MAPCPUOSPECIALS2 "Probability that the guard will search for secrets:"
#define DIALOG_MAPCPUOSPECIALS3 "Probability that the guard finds secrets:"
#define DIALOG_MAPCPUORATIO "Ratio (Squares/Lutins)-1:"
#define DIALOG_MAPCPUOSTARTINGMANA "Mana at startup:"
#define DIALOG_MAPCPUOSPEED "Speed:"
#define DIALOG_MAPCPUOMANA "Mana:"
#define DIALOG_MAPCPUOGOLD "Gold:"
#define DIALOG_MAPCPUOOPENNESS "Exposure rate:"

#define DIALOG_MAPALLIESTITLE "Modification of alliances"
#define DIALOG_MAPALLIES "Alliances"

#define DIALOG_MAPCREATURESTITLE	"Modification des param�tres des cr�atures"
#define DIALOG_MAPCREATURES "List of creatures"
#define DIALOG_MAPCREATURESPARAMS "Settings for selected creatures"
#define DIALOG_MAPCREATURESRES "Resistance"
#define DIALOG_MAPCREATURESCOR "Courage"
#define DIALOG_MAPCREATURESCHA "Charisma"
#define DIALOG_MAPCREATURESSTR "Strength"

#define DIALOG_MAPVOICETITLE		"Game Voice"
#define DIALOG_MAPVOICEFILE "Sound file"
#define DIALOG_MAPVOICEIDENTIFIERS "Identifiers (SPEECH_MENTOR)"
#define DIALOG_MAPVOICEINTROLEVEL "Level introduction"
#define DIALOG_MAPVOICEVICTORY "Victory"
#define DIALOG_MAPVOICEEDEFEAT "Defeat"
#define DIALOG_MAPVOICEENDLEVEL "End of level"
#define DIALOG_MAPVOICEGENERIC "Generic introduction"
#define DIALOG_MAPVOICELIST "Sounds present in the selected sound file"

#define DIALOG_MAPTXTTITLE		"Game Texts"
#define DIALOG_MAPTXTFILE "Text file"
#define DIALOG_MAPTXTINTRO "Introduction && objectives (Intermediate phases)"
#define DIALOG_MAPTXTINTROTITLE "Title"
#define DIALOG_MAPTXTINTROSPOT "Intrigue"
#define DIALOG_MAPTXTDEBRIEFING "Debriefing"
#define DIALOG_MAPTXTMAINOBJECTIVE "Main objective"
#define DIALOG_MAPTXTSUBOBJECTIVE1 "First secondary objective"
#define DIALOG_MAPTXTSUBOBJECTIVE2 "Second secondary objective"
#define DIALOG_MAPTXTSUBOBJECTIVE3 "Third secondary objective"
#define DIALOG_MAPTXTOVERRIDE "Replacement texts when creatures appear"
#define DIALOG_MAPTXTOVERRIDE1 "1:"
#define DIALOG_MAPTXTOVERRIDE2 "2:"
#define DIALOG_MAPTXTOVERRIDE3 "3:"
#define DIALOG_MAPTXTOVERRIDE4 "4:"
#define DIALOG_MAPTXTOVERRIDE5 "5:"
#define DIALOG_MAPTXTOVERRIDE6 "6:"
#define DIALOG_MAPTXTOVERRIDE7 "7:"
#define DIALOG_MAPTXTOVERRIDE8 "8:"
#define DIALOG_MAPTXTLIST "Text list"

#define DIALOG_MAPVARSTITLE		"Modification des variables du jeu"
#define DIALOG_MAPVARSLIST "Variables"
#define DIALOG_MAPVARSMODIFY "Modify"
#define DIALOG_MAPVARSDEFAULT "Default"

#define DIALOG_MAPOPTIONSTITLE		"Level Options"
#define DIALOG_MAPOPTIONSGAME "Miscellaneous"
#define DIALOG_MAPOPTIONSHORNY "Number of pieces acquired from Horny's talisman"
#define DIALOG_MAPOPTIONSSPEED "Speed of the game"
#define DIALOG_MAPOPTIONSTRACK "Audio track"
#define DIALOG_MAPOPTIONSTYPE "Level type"
#define DIALOG_MAPOPTIONSSECRET "Secret level"
#define DIALOG_MAPOPTIONSSPECIAL "Special level"
#define DIALOG_MAPOPTIONSMULTI "Multiplayer level"
#define DIALOG_MAPOPTIONSSINGLE "Skillful level" 
#define DIALOG_MAPOPTIONSPETDONJON "Small dungeon"
#define DIALOG_MAPOPTIONSPARAMS "Settings"
#define DIALOG_MAPOPTIONSJAIL		"Always Imprison Enemies"
#define DIALOG_MAPOPTIONSCRYSTAL	"Le dernier donjon d�truit g�n�re un cristal"
#define DIALOG_MAPOPTIONSHORNYONE	"Allow only one use of the big horn"
#define DIALOG_MAPOPTIONSOBJECTIVES	"Afficher les objectifs au d�marrage"
#define DIALOG_MAPOPTIONSLOCKOPTIONS	"Blocking the game options"
#define DIALOG_MAPOPTIONSLOCKPOSSESS	"Emp�cher l'arr�t de la possession"
#define DIALOG_MAPOPTIONSKILLEDHEROES	"Afficher le nombre de h�ros tu�s"
#define DIALOG_MAPOPTIONSREWARDS "Rewards"

#define DIALOG_MAPGBLDEFAULT "Default"
#define DIALOG_MAPGBLDEFAULTALL "Default all"
#define DIALOG_MAPGBLTERRAINS "Lands"
#define DIALOG_MAPGBLTNAMES "Modifiable lands"
#define DIALOG_MAPGBLTMAXHEALTH "When energy is at its maximum"
#define DIALOG_MAPGBLTDESTROYED "When the field is destroyed"
#define DIALOG_MAPGBLTBECOME "Becomes"
#define DIALOG_MAPGBLTEFFECT "Effect"
#define DIALOG_MAPGBLTOPTIONS "Settings"
#define DIALOG_MAPGBLTDAMAGE "Modification of creature health"
#define DIALOG_MAPGBLTGOLD "Quantity of gold in the terrain"
#define DIALOG_MAPGBLTHEALTHMAX "Max. energy"
#define DIALOG_MAPGBLTHEALTH "Starting energy"
#define DIALOG_MAPGBLTMANA "Amount of mana generated by the terrain" 
#define DIALOG_MAPGBLTMANAMAX "Mana max."
#define DIALOG_MAPGBLTWIBBLEH "Horizontal deformation"
#define DIALOG_MAPGBLTWIBBLEV "Vertical"
#define DIALOG_MAPGBLTVISIBLE "Visible through the field of perception"
#define DIALOG_MAPGBLTLIGHTS "Lights"
#define DIALOG_MAPGBLTTERRAINLIGHT "Light generated by the terrain"
#define DIALOG_MAPGBLTAMBIANTLIGHT "Ambient light"
#define DIALOG_MAPGBLTLIGHTHEIGHT "Height of the terrain light"
#define DIALOG_MAPGBLROOMS "Rooms
#define DIALOG_MAPGBLRNAMES "Editable rooms"
#define DIALOG_MAPGBLREFFECTS "Effects that can occur in this room"
#define DIALOG_MAPGBLROBJECTS		"Objects that can be found in this room"
#define DIALOG_MAPGBLRFIGHTEFFECT "In combat:"
#define DIALOG_MAPGBLR0 "0:"
#define DIALOG_MAPGBLR1 "1:"
#define DIALOG_MAPGBLR2 "2:"
#define DIALOG_MAPGBLR3 "3:"
#define DIALOG_MAPGBLR4 "4:"
#define DIALOG_MAPGBLR5 "5:"
#define DIALOG_MAPGBLRPARAMS "Parameters"
#define DIALOG_MAPGBLRCOST "Cost of a room square"
#define DIALOG_MAPGBLRLIGHT "Torch light"
#define DIALOG_MAPGBLRINTENSITY "Intensity"
#define DIALOG_MAPGBLRHEIGHT "Height"
#define DIALOG_MAPGBLRRADIUS "Radius"
#define DIALOG_MAPGBLDOORS "Doors"
#define DIALOG_MAPGBLDNAMES "Modifiable doors"
#define DIALOG_MAPGBLDMATERIAL "Hardware options"
#define DIALOG_MAPGBLDMATERIALTYPE "Hardware type"
#define DIALOG_MAPGBLDDEATHEFFECT "Effect on destruction"
#define DIALOG_MAPGBLDCRATE "Chest"
#define DIALOG_MAPGBLDKEY "Lock"
#define DIALOG_MAPGBLDCOST "Gold cost"
#define DIALOG_MAPGBLDBUILD "Manufacturing points"
#define DIALOG_MAPGBLDHEALTH "Energy"
#define DIALOG_MAPGBLDHEALTHGAIN "Regeneration"
#define DIALOG_MAPGBLDMANACOST "Mana cost"
#define DIALOG_MAPGBLDPARAMS "Parameters"
#define DIALOG_MAPGBLTRAPS "Traps"
#define DIALOG_MAPGBLANAMES "Modifiable traps"
#define DIALOG_MAPGBLAEFFECTS "Effects"
#define DIALOG_MAPGBLADEATH "Destruction"
#define DIALOG_MAPGBLAMANA "No mana"
#define DIALOG_MAPGBLAIDLE "Inactive"
#define DIALOG_MAPGBLAIDLEDELAY "Interval between each triggering of the inactive effect"
#define DIALOG_MAPGBLAFLAGS "Flags"
#define DIALOG_MAPGBLAINVISIBLE "Invisible"
#define DIALOG_MAPGBLADISARMABLE "Can be disarmed"
#define DIALOG_MAPGBLAREVEAL "Appears after triggering"
#define DIALOG_MAPGBLAUSEMANA "Requires mana"
#define DIALOG_MAPGBLASOLIDOBSTACLE "Solid obstacle"
#define DIALOG_MAPGBLAFPSOLID "Solid obstacle (possession)"
#define DIALOG_MAPGBLAPARAMS "Parameters"
#define DIALOG_MAPGBLAHEALTH "Energy"
#define DIALOG_MAPGBLAHEALTHGAIN "Regeneration"
#define DIALOG_MAPGBLACHARGETIME "Loading time"
#define DIALOG_MAPGBLARECHARGETIME "Time to reload"
#define DIALOG_MAPGBLAGOLDCOST "Gold cost"
#define DIALOG_MAPGBLAMANACOST "Cost in mana"
#define DIALOG_MAPGBLAMANACOSTTOFIRE	"Mana pour tirer"
#define DIALOG_MAPGBLAMANAUSAGE "Mana used"
#define DIALOG_MAPGBLATHREAT "Threat"
#define DIALOG_MAPGBLATHREATDURATION "Threat duration"
#define DIALOG_MAPGBLATRIGGER "Type of activation"
#define DIALOG_MAPGBLASHOT "Spell type"
#define DIALOG_MAPGBLAOPT "?"
#define DIALOG_MAPGBLSPELLS "Spells"
#define DIALOG_MAPGBLSNAMES "Modifiable spells"
#define DIALOG_MAPGBLSCURSOR "Cursor"
#define DIALOG_MAPGBLSOK "Default"
#define DIALOG_MAPGBLSNOGO "Cannot be launched"
#define DIALOG_MAPGBLSRULES "Usage rules"
#define DIALOG_MAPGBLSCAST "Launch"
#define DIALOG_MAPGBLSTARGET "Target"
#define DIALOG_MAPGBLSPARAMS "Settings"
#define DIALOG_MAPGBLSMANACOST "Mana cost"
#define DIALOG_MAPGBLSMANADRAIN "Amount of mana used"
#define DIALOG_MAPGBLSRECHARGETIME "Delay before next use"
#define DIALOG_MAPGBLSBONUSTIME "Bonus time after upgrade"
#define DIALOG_MAPGBLSATTACKING "Attack spell"
#define DIALOG_MAPGBLSDEFENSIVE "Defense Spell"
#define DIALOG_MAPGBLSSHOTS "Spells"
#define DIALOG_MAPGBLSTYPE "Normal"
#define DIALOG_MAPGBLSUPGRADE "Enhanced"
#define DIALOG_MAPGBLOPTIONSTYPE "Activation settings"
#define DIALOG_MAPGBLOPTIONSSHOTS "Spell settings"
#define DIALOG_MAPGBLOPTIONS1 "First data"
#define DIALOG_MAPGBLOPTIONS2 "Second data"
#define DIALOG_MAPGBLOPTIONSCR "Select a creature"
#define DIALOG_MAPGBLOPTIONSOB "Select an object"
#define DIALOG_MAPGBLOPTIONSCOUNT "Number of creatures"
#define DIALOG_MAPGBLOPTIONSLEVEL "Level of the creature"
#define DIALOG_MAPGBLOPTIONSGOLD "Amount of gold"

#define DIALOG_MAPGCREATURES "Available creatures"
#define DIALOG_MAPGCRATTRIBUTES		"Attributs"
#define DIALOG_MAPGCRATTRLIST "Attribute list"
#define DIALOG_MAPGCRATTRDEFAULT "Default value"
#define DIALOG_MAPGCRATTRVALUE "New value"
#define DIALOG_MAPGCRPARAMS "Parameters"
#define DIALOG_MAPGCRPARAMSTYPES "Types"
#define DIALOG_MAPGCRPARAMSARMOUR "Armor"
#define DIALOG_MAPGCRPARAMSFIGHT "Fighter style"
#define DIALOG_MAPGCRPARAMSCLASS "Category"
#define DIALOG_MAPGCRPARAMSBED "Bed"
#define DIALOG_MAPGCRPARAMSEFFECTS "Effects"
#define DIALOG_MAPGCRPARAMSSLAP "During a move"
#define DIALOG_MAPGCRPARAMSHEALTH "During a regeneration"
#define DIALOG_MAPGCRPARAMSENTRANCE "When entering a gate".
#define DIALOG_MAPGCRPARAMSDEATH "At death"
#define DIALOG_MAPGCRPARAMSATTRACT "This creature is attracted..."
#define DIALOG_MAPGCRPARAMSATTRACT1 "...by..."
#define DIALOG_MAPGCRPARAMSATTRACT2 "...and..."
#define DIALOG_MAPGCRFLAGS "Flags
#define DIALOG_MAPGCRFLAG00 "Train in case of inactivity"
#define DIALOG_MAPGCRFLAG01 "Can be caught"
#define DIALOG_MAPGCRFLAG02 "Can be hit"
#define DIALOG_MAPGCRFLAG03 "Can walk on water"
#define DIALOG_MAPGCRFLAG04 "Can walk on lava"
#define DIALOG_MAPGCRFLAG05 "Can be hypnotized"
#define DIALOG_MAPGCRFLAG06 "Immune to the indoctrination spell"
#define DIALOG_MAPGCRFLAG07 "Immune to the galinamorphosis spell"
#define DIALOG_MAPGCRFLAG08 "Immune to the lightning spell"
#define DIALOG_MAPGCRFLAG09 "Generates a corpse in case of death"
#define DIALOG_MAPGCRFLAG10 "Does not get angry with enemy creatures"
#define DIALOG_MAPGCRFLAG11 "Frees its allies in case of escape"
#define DIALOG_MAPGCRFLAG12 "Makes traps appear in the surroundings"
#define DIALOG_MAPGCRFLAG13 "Is not afraid of anything
#define DIALOG_MAPGCRFLAG14 "Doesn't feel any emotion"
#define DIALOG_MAPGCRFLAG15 "Use this creature in random hero strips"
#define DIALOG_MAPGCRATTACKS "Attacks"
#define DIALOG_MAPGCRATTACKSHOTS "Spells"
#define DIALOG_MAPGCRATTACKSHOT1 "First"
#define DIALOG_MAPGCRATTACKSHOT2 "Second"
#define DIALOG_MAPGCRATTACKSHOT3 "Third"
#define DIALOG_MAPGCRATTACKSHOTDELAY "Delay"
#define DIALOG_MAPGCRATTACKSHOTLEVEL "Available at level"
#define DIALOG_MAPGCRATTACKSHOTX "Offset X"
#define DIALOG_MAPGCRATTACKSHOTY "Offset Y"
#define DIALOG_MAPGCRATTACKSHOTZ "Offset Z"
#define DIALOG_MAPGCRATTACKMELEE "Body to body"
#define DIALOG_MAPGCRATTACKMELEETYPE "Weapon type"
#define DIALOG_MAPGCRATTACKMELEETIME "Time to reload"
#define DIALOG_MAPGCRATTACKMELEERANGE "Shot range"
#define DIALOG_MAPGCRATTACKMELEEDMG "Power of the shot"
#define DIALOG_MAPGCRATTACKMELEEDELAY "Delay"
#define DIALOG_MAPGCRRESISTANCES "Resistances"
#define DIALOG_MAPGCRRESISTANCE1 "Resist..."
#define DIALOG_MAPGCRRESISTANCE2 "...and to..."
#define DIALOG_MAPGCRRESISTANCE0PC "0%"
#define DIALOG_MAPGCRRESISTANCE100PC "100%"
#define DIALOG_MAPGCRPOSSESSION "Possession"
#define DIALOG_MAPGCR1STSPECIALS "Special capabilities"
#define DIALOG_MAPGCR1STSPECIAL1 "Capacity 1"
#define DIALOG_MAPGCR1STSPECIAL2 "Capacity 2"
#define DIALOG_MAPGCR1STSWIPE "Hits"
#define DIALOG_MAPGCR1STSWIPEMELEE1 "Hand-to-hand 1"
#define DIALOG_MAPGCR1STSWIPEMELEE2 "Hand-to-hand 2"
#define DIALOG_MAPGCR1STSWIPESPECIAL1 "Special 1"
#define DIALOG_MAPGCR1STSWIPESPECIAL2 "Special 2"
#define DIALOG_MAPGCR1STSWIPESPELL "Sort"
#define DIALOG_MAPGCR1STMOVEMENT "View & Movements"
#define DIALOG_MAPGCR1STGAMMA "Visual filter"
#define DIALOG_MAPGCR1STWADDLE "Waddle"
#define DIALOG_MAPGCR1STOSCILLATE "Oscillation"
#define DIALOG_MAPGCR1STWALK "Walking cycle"
#define DIALOG_MAPGCR1STCAMERA "The camera rolls when the creature turns"
#define DIALOG_MAPGCRJOBS "Occupations"
#define DIALOG_MAPGCRJOBHAPPY "Occupations when the creature is happy"
#define DIALOG_MAPGCRJOBUNHAPPY "Occupations when the creature is unhappy"
#define DIALOG_MAPGCRJOBANGRY "Occupations when the creature is angry"
#define DIALOG_MAPGCRJOBHATE "Occupations the creature hates"
#define DIALOG_MAPGCRJOBCHANCE "Chance"
#define DIALOG_MAPGCRJOBMOOD "Mood"
#define DIALOG_MAPGCRJOBMANA "Mana"
#define DIALOG_MAPGCRJOBADD ">>"
#define DIALOG_MAPGCRJOBREM "<<"
#define DIALOG_MAPGCRLIGHT "Light"
#define DIALOG_MAPGCRLIGHTPOS "Positioning"
#define DIALOG_MAPGCRLIGHTX "X axis"
#define DIALOG_MAPGCRLIGHTY "Y axis"
#define DIALOG_MAPGCRLIGHTZ "Z axis"
#define DIALOG_MAPGCRLIGHTPARAMS "Parameters"
#define DIALOG_MAPGCRLIGHTRADIUS "Radius"
#define DIALOG_MAPGCRLIGHTRGB "Color"
#define DIALOG_MAPGCRLIGHTFLAGS "Flags"
#define DIALOG_MAPGCRLIGHTFLICKER "Glitter"
#define DIALOG_MAPGCRLIGHTPULSE "Pulses"
#define DIALOG_MAPGCRLIGHTPLAYER "Same color as the player"
#define DIALOG_MAPGCRSPELLS "Spells"
#define DIALOG_MAPGCRSPELLSLIST "Available spells"
#define DIALOG_MAPGCRSPELLPARAMS "Settings"
#define DIALOG_MAPGCRSPELLTIME "Time to reload"
#define DIALOG_MAPGCRSPELLRANGE "Range"
#define DIALOG_MAPGCRSPELLSHOT "Spell type"
#define DIALOG_MAPGCRSPELLFLAGS "Flags"
#define DIALOG_MAPGCRSPELLATTACK "Attack spell"
#define DIALOG_MAPGCRSPELLDEFENSIVE "Defense Spell"
#define DIALOG_MAPGCRSPELLCREATURE "Creature spell"
#define DIALOG_MAPGCRSPELLCASTONSELF "The creature uses this spell on itself" 
#define DIALOG_MAPGCRSPELLCASTONOTHERS	"La cr�ature utilise ce sort sur les autres"
#define DIALOG_MAPGCRSPELLCREATURES "This spell is only used on creatures"
#define DIALOG_MAPGCRSPELLUSEDBY "Creatures using this spell"

#define DIALOG_NEWTITLE "New card..."
#define DIALOG_NEWVERSION "Version"
#define DIALOG_NEWPLAYERS "Players"
#define DIALOG_NEWMAPNAME		"Map name"
#define DIALOG_NEWSIZE "Dimensions"
#define DIALOG_NEWWIDTH "Width:"
#define DIALOG_NEWHEIGHT "Height:"
#define DIALOG_NEWSQUARE "Square card"
#define DIALOG_NEWFILLWITH "Fill the map with..."

#define DIALOG_STATSEDITTITLE		"Edition"
#define DIALOG_STATSEDIT "Map"
#define DIALOG_STATSEDITTIME "Total editing time (DD/HH:MM:SS)"
#define DIALOG_STATSLMB "Number of left clicks performed"
#define DIALOG_STATSRMB "Number of right clicks made"
#define DIALOG_STATSUNDO		"Nombre d'annulation effectu�es"
#define DIALOG_STATSPAINT "Detail of operations performed"
#define DIALOG_STATSPAINTTHINGS "Number of objects placed"
#define DIALOG_STATSPAINTFILL "Number of fills performed"
#define DIALOG_STATSPAINTMODE "Number of shapes made"
#define DIALOG_STATSPAINTRNDMODE "Number of random shapes made"
#define DIALOG_STATSFILES "Files"
#define DIALOG_STATSSAVECOUNT "Number of saves made"
#define DIALOG_STATSCREATEDTIME "Creation of the map"
#define DIALOG_STATSCOMPILETIME		"Derni�re compilation avant la sauvegarde"
#define DIALOG_STATSLASTSAVE "Last backup done"
#define DIALOG_STATSMAPTITLE "Map"
#define DIALOG_STATSMAPELEMS "Elements"
#define DIALOG_STATSMAPCREATURES "Number of creatures -- Most used"
#define DIALOG_STATSMAPLVLCREATURE "Average level of creatures"
#define DIALOG_STATSMAPTRAPS "Number of traps -- Most used"
#define DIALOG_STATSMAPDOORS "Number of doors -- Most used"
#define DIALOG_STATSMAPOBJECTS "Number of objects -- Most used"
#define DIALOG_STATSMAPMAGICS "Number of magic objects -- Most used"
#define DIALOG_STATSMAPTERRAIN "Lands"
#define DIALOG_STATSMAPTOTAL "Number of squares in the map"
#define DIALOG_STATSMAPWATER "Water squares"
#define DIALOG_STATSMAPLAVA "Lava squares"
#define DIALOG_STATSMAPSOLID "Squares of impenetrable rock"
#define DIALOG_STATSMAPROCK "Soft rock squares"
#define DIALOG_STATSMAPUNCLAIMED "Unclaimed land squares"
#define DIALOG_STATSMAPREL "% of total"
#define DIALOG_STATSMAPGOLD "Gold"
#define DIALOG_STATSMAPTOTALGOLD "Gold in the whole level"
#define DIALOG_STATSMAPOBJECTSGOLD "Gold in objects"
#define DIALOG_STATSMAPMAGICSGOLD "Gold contained in magic objects"
#define DIALOG_STATSMAPGEMS "The level contains gems"
#define DIALOG_STATSPLAYERSTITLE "Players"
#define DIALOG_STATSPLYIMPS "Number of gems"
#define DIALOG_STATSPLYBUILDINGS "Constructions"
#define DIALOG_STATSPLYHEART "Position of the heart of the dungeon"
#define DIALOG_STATSPLYGOLD "Capacity of the treasure rooms"
#define DIALOG_STATSPLYROOM "Capacity of the dens"
#define DIALOG_STATSPLYMANA "Mana regeneration"
#define DIALOG_STATSPLYWALLS "Number of consolidated walls"
#define DIALOG_STATSPLYCLAIMED "Number of squares claimed"
#define DIALOG_STATSBANDSTITLE "Hero Bands"
#define DIALOG_STATSBANDSHEROES "Heroes statistics with heroes bands"
#define DIALOG_STATSBANDSALL "Statistics of all heroes bands"
#define DIALOG_STATSBANDSCREATURES "Number of creatures"
#define DIALOG_STATSBANDSDWARFS "Number of dwarf pickers"
#define DIALOG_STATSBANDS "Statistics per band"
#define DIALOG_STATSBANDSLEVELS "Dwarfs and sprites are included in the calculation"
#define DIALOG_STATSBANDUSECOUNT "Number of uses"

#define DIALOG_TRIGGERS			"Events..."
#define DIALOG_TRIGGERSOWNER		"Action Points"
#define DIALOG_TRIGGERSLIST "List of conditions and actions"
#define DIALOG_TRIGGERSADD "Add"
#define DIALOG_TRIGGERSINS "Insert"
#define DIALOG_TRIGGERSMOD "Modify"
#define DIALOG_TRIGGERSDEL "Delete"
#define DIALOG_TRIGGERSADDROOT "Add to root"
#define DIALOG_TRIGGERSTRIGGER "Trigger"
#define DIALOG_TRIGGERSACTION "Action"
#define DIALOG_TRIGGERSSELECTION "Selection"
#define DIALOG_TRIGGERSVARIABLES "Variables && counters"
#define DIALOG_TRIGGERSVRVARLIST "List of variables"
#define DIALOG_TRIGGERSVRTIMLIST "List of counters"
#define DIALOG_TRIGGERSVRNAME "Change name"
#define DIALOG_TRIGGERSPTTITLE "Action points..."
#define DIALOG_TRIGGERSPTLIST "Select action point type"
#define DIALOG_TRIGGERSPTLEVEL "Level"
#define DIALOG_TRIGGERSPTKEEPER "Keeper"
#define DIALOG_TRIGGERSPTCREATURE "Creature"
#define DIALOG_TRIGGERSPTDOOR "Door"
#define DIALOG_TRIGGERSPTOBJECT "Object"
#define DIALOG_TRIGGERSPTMAGIC "Magic object"
#define DIALOG_TRIGGERSPTAREA "Area"
#define DIALOG_TRIGGERSPTBAND "Band of heroes
#define DIALOG_TRIGGERSPTBANDCREATURE "Creature in a band of heroes
#define DIALOG_TRIGGERSPTPLAYERS "Select a player"
#define DIALOG_TRIGGERSPTPLYLIST "List of players"
#define DIALOG_TRIGGERSPTCREATURES "Select creature"
#define DIALOG_TRIGGERSPTCREATURESLIST "List of creatures"
#define DIALOG_TRIGGERSPTDOORS "Select the concerned door"
#define DIALOG_TRIGGERSPTDOORSLIST "List of doors"
#define DIALOG_TRIGGERSPTOBJECTS	"S�lectionnez l'objet concern�"
#define DIALOG_TRIGGERSPTOBJECTSLIST "List of objects"
#define DIALOG_TRIGGERSPTMAGICS "Select the concerned magic object"
#define DIALOG_TRIGGERSPTMAGICSLIST "List of magical objects"
#define DIALOG_TRIGGERSPTAREAS "Select the concerned area"
#define DIALOG_TRIGGERSPTAREASLIST "List of zones"
#define DIALOG_TRIGGERSPTBANDS "Select the concerned hero band"
#define DIALOG_TRIGGERSPTBANDSLIST "List of hero bands"
#define DIALOG_TRIGGERSTITLE "Triggers..."
#define DIALOG_TRIGGERSTYPETITLE "Select trigger type"
#define DIALOG_TRIGGERSTYPELIST "List of triggers"
#define DIALOG_TRIGGERSVARTITLE "Test a variable"
#define DIALOG_TRIGGERSVARLO "Less than"
#define DIALOG_TRIGGERSVARLS "Less than or equal to"
#define DIALOG_TRIGGERSVAREQ "Equal to"
#define DIALOG_TRIGGERSVARHI "Greater than"
#define DIALOG_TRIGGERSVARHS "Greater than or equal to"
#define DIALOG_TRIGGERSVARNE "Different from"
#define DIALOG_TRIGGERSTIMERTITLE "Test of a counter
#define DIALOG_TRIGGERSTIMERLO "Less than"
#define DIALOG_TRIGGERSTIMERLS "Less than or equal to"
#define DIALOG_TRIGGERSTIMEREQ "Equal to"
#define DIALOG_TRIGGERSTIMERHI "Greater than"
#define DIALOG_TRIGGERSTIMERHS "Greater than or equal to"
#define DIALOG_TRIGGERSTIMERNE "Different from"
#define DIALOG_TRIGGERSTIMERSECS "Dry"
#define DIALOG_TRIGGERSRTTYPE "Account for..."
#define DIALOG_TRIGGERSRTBLUEPRINTS "Sketches"
#define DIALOG_TRIGGERSRTBUILDS "The constructions"
#define DIALOG_TRIGGERSRTALL "All"
#define DIALOG_TRIGGERSELAPSEDTITLE "Time elapsed since the beginning of the game"
#define DIALOG_TRIGGERSELAPSEDTEXT "Number of seconds elapsed (in seconds of the game)"
#define DIALOG_TRIGGERSTIMETEXT "Time (HH:MM:SS)"
#define DIALOG_TRIGGERSCREATURES "Number of creatures possessed by the player"
#define DIALOG_TRIGGERSCREATURESTYPE "List of creatures"
#define DIALOG_TRIGGERSCREATURESELITE "Note: Elites are not counted"
#define DIALOG_TRIGGERSCREATURESCOUNT "Player must have..."
#define DIALOG_TRIGGERSCREATURESLO "Less than"
#define DIALOG_TRIGGERSCREATURESLS "At most"
#define DIALOG_TRIGGERSCREATURESEQ "A number equal to"
#define DIALOG_TRIGGERSCREATURESHI "More than"
#define DIALOG_TRIGGERSCREATURESHS "At least"
#define DIALOG_TRIGGERSCREATURESNE "A different number of"
#define DIALOG_TRIGGERSHAPPYCREATURES "Number of happy creatures possessed by the player"
#define DIALOG_TRIGGERSANGRYCREATURES "Number of angry creatures possessed by the player"
#define DIALOG_TRIGGERSLOSTCREATURES "Number of lost creatures by the player"
#define DIALOG_TRIGGERSLOSTCOUNT "Player must lose some..."
#define DIALOG_TRIGGERSLOSTKILLBY "Responsible for the death of the creatures"
#define DIALOG_TRIGGERSKILLEDCREATURES "Number of creatures killed by the player
#define DIALOG_TRIGGERSKILLEDCOUNT "Player must kill some..."
#define DIALOG_TRIGGERSKILLEDOWNER "Owner of the killed creatures"
#define DIALOG_TRIGGERSLEVELCREATURES "Level reached by player's creatures" 
#define DIALOG_TRIGGERSLEVELCOUNT	"Nombre de cr�atures devant atteindre ce niveau..."
#define DIALOG_TRIGGERSLEVELTEXT	"Niveau � atteindre"
#define DIALOG_TRIGGERSLEVELNOTE	"Note: Les lutins ne sont pas inclus"
#define DIALOG_TRIGGERSSQUARES		"Nombre de carr�s de salles poss�d�s par le joueur"
#define DIALOG_TRIGGERSROOMSSIZE "Number of squares per room"
#define DIALOG_TRIGGERSROOMSCONTENT "Number of objects in the rooms"
#define DIALOG_TRIGGERSROOMSTYPE "List of rooms"
#define DIALOG_TRIGGERSROOMSSQUARES "Squares used by the room..."
#define DIALOG_TRIGGERSROOMSOBJECTS "The room must contain..."
#define DIALOG_TRIGGERSROOMS "Number of rooms owned by the player"
#define DIALOG_TRIGGERSDOORS "Number of doors owned by the player"
#define DIALOG_TRIGGERSDOORSTYPE "List of doors"
#define DIALOG_TRIGGERSDESTROYED "Number of doors and traps destroyed by the player"
#define DIALOG_TRIGGERSDESTROYEDTYPE "List of doors and traps"
#define DIALOG_TRIGGERSDESTROYEDCOUNT "The player must destroy..."
#define DIALOG_TRIGGERSTRAPS "Number of traps owned by the player"
#define DIALOG_TRIGGERSTRAPSTYPE "List of traps"
#define DIALOG_TRIGGERSSPELLS "Spell discovered by the player"
#define DIALOG_TRIGGERSSPELLSTYPE "List of spells"
#define DIALOG_TRIGGERSGOLDMINED "Amount of gold collected by the player"
#define DIALOG_TRIGGERSGOLDTEXT "Amount of gold"
#define DIALOG_TRIGGERSGOLDAMOUNT "Amount of gold held by the player"
#define DIALOG_TRIGGERSMANAAMOUNT "Amount of mana available to the player"
#define DIALOG_TRIGGERSMANATEXT "Amount of mana"
#define DIALOG_TRIGGERSSLAP "Number of moves given by the player"
#define DIALOG_TRIGGERSSLAPCOUNT "Number of moves the player must give..."
#define DIALOG_TRIGGERSINTERFACE "The player presses a button on the interface"
#define DIALOG_TRIGGERSBUTTONS "List of buttons"
#define DIALOG_TRIGGERSPOSSESS		"Groupe de cr�atures lors de l'utilisation du sort possession"
#define DIALOG_TRIGGERSPOSSESSCOUNT "Number of creatures to group..."
#define DIALOG_TRIGGERSHEART "Heart of the dungeon destroyed"
#define DIALOG_TRIGGERSHEARTTEXT "Responsible for the destruction"
#define DIALOG_TRIGGERSDEATHS "Number of dead in a bunch of heroes"
#define DIALOG_TRIGGERSHEROSBANDS "List of heroes bands
#define DIALOG_TRIGGERSBANDCREATED "Creation of a band of heroes
#define DIALOG_TRIGGERSDEATHSCOUNT "Number of creatures to be killed..."
#define DIALOG_TRIGGERSSTUNNED "Number of stunned creatures in a hero band"
#define DIALOG_TRIGGERSSTUNNEDCOUNT "Number of creatures to be stunned..."
#define DIALOG_TRIGGERSJAILED "Number of prisoners in a band of heroes"
#define DIALOG_TRIGGERSJAILEDCOUNT "Number of creatures to be taken prisoner..."
#define DIALOG_TRIGGERSHURTED "Vitality of the creature"
#define DIALOG_TRIGGERSVITALITY "The percentage of vitality remaining must be..."
#define DIALOG_TRIGGERSPERCENT		"%"
#define DIALOG_TRIGGERSENTERAREAPS "A player is in the zone with a creature in possession."
#define DIALOG_TRIGGERSENTERAREAPSTEXT "List of players"
#define DIALOG_TRIGGERSENTERAREACP "Creatures are in the zone"
#define DIALOG_TRIGGERSENTERAREACPCT "Number of creatures that should be in the zone..."
#define DIALOG_TRIGGERSENTERAREACPPL "Player who owns the creatures"
#define DIALOG_TRIGGERSCLAIMAREA "A player has claimed squares in the zone"
#define DIALOG_TRIGGERSCLAIMAREAPL	"Joueur qui doit r�clamer la zone"
#define DIALOG_TRIGGERSCLAIMAREACT "Number of squares the player must claim..."
#define DIALOG_TRIGGERSCLAIMALLAREA "A player claims the whole area"
#define DIALOG_TRIGGERSCLAIMALLAREATXT "Player who has claimed the zone"
#define DIALOG_TRIGGERSAREACONTENT "Content of the zone"
#define DIALOG_TRIGGERSAREACONTENTTR "Field contained in the zone"
#define DIALOG_TRIGGERSAREACONTENTCT "Number of squares to contain this land..."
#define DIALOG_TRIGGERSMAPOWNER "Player who should hold the field"
#define DIALOG_TRIGGERSSELECTAREA "A player selects the area"
#define DIALOG_TRIGGERSSELECTAREAPL "Player to select the area"
#define DIALOG_TRIGGERSSELECTAREACT "Number of squares to be selected..."
#define DIALOG_TRIGGERSSELALLAREA "A player selects the whole area"
#define DIALOG_TRIGGERSSELALLAREATXT "Player to select the area"
#define DIALOG_TRIGGERSCREATURELEVEL "Level of the creature
#define DIALOG_TRIGGERSCREATURELVLCNT "The level of the creature must be..."
#define DIALOG_TRIGGERSREPEATTITLE "Number of times the trigger has been used"
#define DIALOG_TRIGGERSREPEATONETEXT "Only once"
#define DIALOG_TRIGGERSREPEATMORETEXT "times"
#define DIALOG_TRIGGERSREPEATINFTEXT "No limit"

#define DIALOG_ACTIONSTITLE		"Actions..."
#define DIALOG_ACTIONSTYPETITLE "Select action type"
#define DIALOG_ACTIONSTYPELIST "List of actions"
#define DIALOG_ACTIONSVARDST "Target variable"
#define DIALOG_ACTIONSVARSRC "Source variable"
#define DIALOG_ACTIONSVARTITLE "Variable modification"
#define DIALOG_ACTIONSVARSET "Place"
#define DIALOG_ACTIONSVARADD "Add"
#define DIALOG_ACTIONSVARSUB "Subtract"
#define DIALOG_ACTIONSVARVARSET "Place the value of the source variable"
#define DIALOG_ACTIONSVARVARADD "Add the value of the source variable"
#define DIALOG_ACTIONSVARVARSUB "Subtract the value of the source variable"
#define DIALOG_ACTIONSTIMTITLE "Activate a counter"
#define DIALOG_ACTIONSCREATURETITLE "Adding a creature"
#define DIALOG_ACTIONSCREATURETYPE "Creature to add"
#define DIALOG_ACTIONSCREATURELEVEL "Level"
#define DIALOG_ACTIONSCREATUREOWNER	"Joueur qui re�oit la cr�ature"
#define DIALOG_ACTIONSCREATUREOPTIONS "Creature options"
#define DIALOG_ACTIONSCREATUREX		"X:"
#define DIALOG_ACTIONSCREATUREY		"Y:"
#define DIALOG_ACTIONSCREATUREAREA "Use the starting positions of the area..."
#define DIALOG_ACTIONSELEM "Add/Remove an element"
#define DIALOG_ACTIONSELEMLIST "List of elements"
#define DIALOG_ACTIONSELEMPLAYER "Affected player"
#define DIALOG_ACTIONSELEMADD "Add the element"
#define DIALOG_ACTIONSELEMSUB "Delete the item"
#define DIALOG_ACTIONSSHOW "Enable/Disable zone illumination"
#define DIALOG_ACTIONSSHOWAREA "Affected area"
#define DIALOG_ACTIONSSHOWDEACTIVATE	"D�sactiver l'illumination"
#define DIALOG_ACTIONSSHOWACTIVATE	"Activer l'illumination"
#define DIALOG_ACTIONSVISIBLE "Enable/Disable the fog of war"
#define DIALOG_ACTIONSVISIBLEAREA "Affected area"
#define DIALOG_ACTIONSVISIBLESHOW "Deactivate the fog of war"
#define DIALOG_ACTIONSVISIBLEHIDE "Activate the fog of war"
#define DIALOG_ACTIONSBAND "Free a band of heroes"
#define DIALOG_ACTIONSHEROSLIST "Bunch of heroes to free
#define DIALOG_ACTIONSBANDAREA "Area in which heroes must be freed"
#define DIALOG_ACTIONSBANDINVASION "Invaders in a small dungeon"
#define DIALOG_ACTIONSBANDRANDOM "Randomly define the type of creatures"
#define DIALOG_ACTIONSGATE "Destroy a hero portal"
#define DIALOG_ACTIONSGATENAME "Destroy portal"
#define DIALOG_ACTIONSSQUARE		"Changer un carr� de terrain"
#define DIALOG_ACTIONSSQUARESOFT	"Terrain de remplacement"
#define DIALOG_ACTIONSSQUAREOWNER "Player holding the new field"
#define DIALOG_ACTIONSSQUARERECT	"Changer tout un rectangle"
#define DIALOG_ACTIONSSQUAREBRIDGES "Note: bridges are placed on water"
#define DIALOG_ACTIONSLIGHT "Turn on/off stars/flashing on a button"
#define DIALOG_ACTIONSLIGHTLIST "List of buttons"
#define DIALOG_ACTIONSLIGHTSET		"Activer les �toiles/le clignotement"
#define DIALOG_ACTIONSLIGHTCLEAR "Disable stars/blinking".
#define DIALOG_ACTIONSLIGHTTIME "Flashing duration"
#define DIALOG_ACTIONSSAY "Say something"
#define DIALOG_ACTIONSSAYNAME "Voice identifier"
#define DIALOG_ACTIONSSAYNOTEXT "Don't show matching text"
#define DIALOG_ACTIONSVIEW "Activate/Deactivate the kinematic view"
#define DIALOG_ACTIONSVIEWSET "Activate the kinematic view"
#define DIALOG_ACTIONSVIEWCLEAR "Disable kinematic view"
#define DIALOG_ACTIONSMOVECAMERA	"D�placer la cam�ra au-dessus d'une zone"
#define DIALOG_ACTIONSMOVECAMERAAREA "Target area"
#define DIALOG_ACTIONSROTATECAMERA "Rotate camera over a zone"
#define DIALOG_ACTIONSROTATEANGLE "Rotation angle (in degrees)"
#define DIALOG_ACTIONSROTATEWAIT "Duration (in seconds)"
#define DIALOG_ACTIONSROOM "Show next room"
#define DIALOG_ACTIONSROOMLIST "Room to display"
#define DIALOG_ACTIONSSLAPS "Display the number of remaining slaps"
#define DIALOG_ACTIONSSLAPSTEXT "Number of slaps (0 to disable display)"
#define DIALOG_ACTIONSTIMER "Display the remaining time"
#define DIALOG_ACTIONSTIMERTEXT "Number of seconds"
#define DIALOG_ACTIONSTIMERDISABLE "A time equal to 00:00:00 disables the display"
#define DIALOG_ACTIONSTARGET "Designate as primary target"
#define DIALOG_ACTIONSTARGETCLEAR "Disable designation"
#define DIALOG_ACTIONSTARGETFIGHT "Enemy to be shot"
#define DIALOG_ACTIONSTARGETJAIL "Enemy to be imprisoned"
#define DIALOG_ACTIONSTARGETTORTURE "Enemy to be converted"
#define DIALOG_ACTIONSPARAMS		"Modifier les param�tres de la cr�ature"
#define DIALOG_ACTIONSPARAMSPLLIST "Target player"
#define DIALOG_ACTIONSPARAMSAREA "Target area"
#define DIALOG_ACTIONSPARAMSROOMS "Creature destroys enemy rooms"
#define DIALOG_ACTIONSPARAMSWALLS "The creature destroys the enemy walls"
#define DIALOG_ACTIONSPARAMSGOLD "Creature steals enemy gold"
#define DIALOG_ACTIONSPARAMSSPELLS "Creature steals enemy's spells"
#define DIALOG_ACTIONSPARAMSCRATES "Creature steals enemy's crates"
#define DIALOG_ACTIONSPARAMSKILL "Creature kills enemy's creatures"
#define DIALOG_ACTIONSPARAMSATTACK "Creature attacks player"
#define DIALOG_ACTIONSPARAMSSTAY "The creature stays in place"
#define DIALOG_ACTIONSPARAMSGO "Creature is trying to reach the area"
#define DIALOG_ACTIONSPARAMSJAIL "The creature tries to escape"
#define DIALOG_ACTIONSRUN "Make the creature run"
#define DIALOG_ACTIONSRUNSET		"Make creature run"
#define DIALOG_ACTIONSRUNCLEAR "Stop running the creature"
#define DIALOG_ACTIONSOWNER		"Change the owner of a room"
#define DIALOG_ACTIONSOWNERLIST "New player holding the room"
#define DIALOG_ACTIONSALLIES "Establish/break an alliance"
#define DIALOG_ACTIONSFIRSTALLIE "First player involved"
#define DIALOG_ACTIONSSECONDALLIE "Second player involved"
#define DIALOG_ACTIONSSETALLIANCE "Establish an alliance"
#define DIALOG_ACTIONSCLEARALLIANCE "Break an alliance"
#define DIALOG_ACTIONSGENERATE "Bring a creature out of a portal"
#define DIALOG_ACTIONSGENTYPE "Creature to generate"
#define DIALOG_ACTIONSPORTALS		"Changer le statut des portails"
#define DIALOG_ACTIONSPORTALSOPENED "Open portals"
#define DIALOG_ACTIONSPORTALSCLOSED "Close portals"
#define DIALOG_ACTIONSMOODS "Change the mood of the creatures"
#define DIALOG_ACTIONSMOODSON "Activate creature mood"
#define DIALOG_ACTIONSMOODSOFF "Disable creature moods"
#define DIALOG_ACTIONSTIMERSPEECH "Enable/disable voice countdown of remaining time"
#define DIALOG_ACTIONSTIMERSPEECHON "Enable the voice countdown"
#define DIALOG_ACTIONSTIMERSPEECHOFF "Disable voice countdown"
#define DIALOG_ACTIONSCAMERAPATH "Execute a predefined camera movement".
#define DIALOG_ACTIONSCAMERAPATHAREA "Zone from which the movement is triggered"
#define DIALOG_ACTIONSCAMERAPATHID "Identifier of the motion"
#define DIALOG_ACTIONSCAMERAPATHCEON "Display the ceiling"
#define DIALOG_ACTIONSCAMERAPATHCEOFF "Hide ceiling"
#define DIALOG_ACTIONSSYSMSGS "Turn on/off game messages"
#define DIALOG_ACTIONSSYSMSGSON "Enable messages"
#define DIALOG_ACTIONSSYSMSGSOFF "Disable messages"
#define DIALOG_ACTIONSMUSIC "Music level"
#define DIALOG_ACTIONSMUSICSILENCE "0"
#define DIALOG_ACTIONSMUSICFULLVOLUME "100"
#define DIALOG_ACTIONSATTACK "Change creature's attack behavior"
#define DIALOG_ACTIONSATTACKON "The creature attacks"
#define DIALOG_ACTIONSATTACKOFF "The creature does not attack"
#define DIALOG_ACTIONSSHOWHEALTH "Display the petals of the creature"
#define DIALOG_ACTIONSSHOWHEALTHTIME "Display duration (in seconds)"
#define DIALOG_ACTIONSFXTITLE "Activate/deactivate an effect"
#define DIALOG_ACTIONSFXTOGGLE "Effect concerned"
#define DIALOG_ACTIONSFXENABLE "Activate the effect"
#define DIALOG_ACTIONSFXTGLE "Effect concerned"

/*** Menu texts ************************************************************/

#define DIALOG_MENUFILE"File"
#define DIALOG_MENUEDIT "Edit"
#define DIALOG_MENUPAINT "Drawing"
#define DIALOG_MENUDISPLAY "Display"
#define DIALOG_MENUPROPERTIES "Properties"
#define DIALOG_MENUHELP "Help"

/*** Dialog texts (camera paths) **************************/

#define DIALOG_PATHSTITLE "Listed camera paths"
#define DIALOG_PATHSIDENTIFIERS "Identifiers"
#define DIALOG_PATHSINFO "Description of the selected identifier"

/*** Miscellaneous texts ***************************************************************/

#define DIALOG_COPYRIGHT "Map creator for Dungeon Keeper II®\0"
#define DIALOG_PATHSDESCRIPTION "Description of camera paths\0"
